version: "3"
services:
  php:
    build: .
    container_name: "php"
    image: php:8.1.16-apache
    volumes:
      - ./code/:/var/www/html/
    ports:
      - 80:80
  
  db:
    image: mariadb:10.5
    container_name: "mariadb-server"
    restart: always
    volumes:
      - ./code/db/banco.sql:/docker-entrypoint-initdb.d/banco.sql
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
  
  adminer:
    image: adminer:4.8.1
    container_name: "adminer"
    restart: always
    ports:
      - 8080:8080